LES/LES/Models/Entity/Livro.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;

namespace LES.Models.Entity
{
    public class Livro : EntidadeDominio
    {
        public string Titulo { get; set; }
        public int Altura { get; set; }
        public string Autor { get; set; }
        public byte[] Capa { get; set; }
        public string CodigoBarras { get; set; }
        public int Comprimento { get; set; }
        public DateTime DtLancamento { get; set; }
        public int Edicao { get; set; }
        public int EditoraId { get; set; }
        public int Estoque { get; set; }
        public int EstoqueBloqueado { get; set; }
        public int GrupoPrecoId { get; set; }
        public string Isbn { get; set; }
        public int Largura { get; set; }
        public double? MaiorCusto { get; set; }
        public int Paginas { get; set; }
        public double Peso { get; set; }
        public string Sinopse { get; set; }
        public double Valor { get; set; }

        public virtual IList<Ativacao> Ativacoes { get; set; } = new List<Ativacao>();
        public virtual IList<CarrinhoLivro> CarrinhoLivro { get; set; } = new List<CarrinhoLivro>();
        public virtual IList<LivroCategoriaLivro> LivrosCategoriaLivros { get; set; } = new List<LivroCategoriaLivro>();
        public virtual IList<LivroPedido> LivroPedidos { get; set; } = new List<LivroPedido>();
        public virtual Editora Editora { get; set; }
        public virtual GrupoPreco GrupoPreco { get; set; }
        public virtual IList<Inativacao> Inativacoes { get; set; } = new List<Inativacao>();

    }

}

LES/LES/Models/ViewModel/Livros/LojaModel.cs
using LES.Models.ViewModel.Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LES.Models.ViewModel.Livros
{
    public class LojaModel
    {
        public LojaFiltrosModel Filtros { get; set; }
        public IList<LivroCardModel> Livros { get; set; }
    }
}

LES/LES/Models/ViewModel/Livros/PaginaLojaModel.cs
using LES.Models.ViewModel.Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LES.Models.ViewModel.Livros
{
    public class PaginaLojaModel : IViewModel
    {
        public LojaFiltrosModel Filtros { get; set; }
        public ListaCardLivrosModel Livros { get; set; }
    }
}

LES/LES/Controllers/CarrinhoCompraController.cs
using LES.Controllers;
using LES.Controllers.Facade;
using LES.Data.DAO;
using LES.Models.Entity;
using LES.Models.Schedulers;
using LES.Models.ViewHelpers.CarrinhoCompra;
using LES.Models.ViewHelpers.Conta;
using LES.Models.ViewHelpers.Shared;
using LES.Models.ViewModel.Carrinho;
using LES.Models.ViewModel.Conta;
using LES.Models.ViewModel.Shared;
using LES.Views.Conta;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Formatters;
using Microsoft.EntityFrameworkCore.Query.Internal;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml;

namespace LES.Views.CarrinhoCompra
{
    [Authorize]
    public class CarrinhoCompraController : BaseController
    {
        IDAOTabelaRel<CarrinhoLivro> _daoCarrinhoLivro { get; set; }
        IDAOTabelaRel<CartaoPedido> _daoCartaoPedido { get; set; }
        IFacadeCrud _facade { get; set; }

        public CarrinhoCompraController(
            IDAOTabelaRel<CarrinhoLivro> daoCarrinhoLivro,
            IDAOTabelaRel<CartaoPedido> daoCartaoPedido,
            IFacadeCrud facade)
        {
            _daoCarrinhoLivro = daoCarrinhoLivro;
            _daoCartaoPedido = daoCartaoPedido;
            _facade = facade;
        }

        public IActionResult FinalizarCompra() {

            Cliente c = GetClienteComEmail();
            Cliente clienteDb = _facade.GetAllInclude(c);
            Carrinho carrinho = clienteDb.Carrinho;

            if (carrinho == null || carrinho.CarrinhoLivro.Count == 0) 
            {
                TempData["Alert"] = "Você não possui livros no carrinho!";
                return RedirectToAction("Loja", "Livros");
            }

            Pedido pedNaoFinalizado = GetPedidoNaoFinalizado(clienteDb);
            bool naoTemPedido = pedNaoFinalizado == null;

            if(naoTemPedido)
            {
                pedNaoFinalizado = new Pedido
                {
                    Endereco = clienteDb.Enderecos
                    .Where(e => e.EFavorito && !e.Inativo).FirstOrDefault()
                };
            }

            pedNaoFinalizado.Cliente = clienteDb;
            pedNaoFinalizado.DtCadastro = DateTime.Now;
            pedNaoFinalizado.Inativo = false;
            pedNaoFinalizado.LivrosPedidos = new List<LivroPedido>();
            foreach (var entry in carrinho.CarrinhoLivro)
                for(int i = 0; i < entry.Quantia; i++)
                    pedNaoFinalizado.LivrosPedidos.Add(new LivroPedido
                    {
                        Livro = entry.Livro,
                        Pedido = pedNaoFinalizado,
                        Trocado = false
                    });
            pedNaoFinalizado.Status = StatusPedidos.NaoFinalizado;

            pedNaoFinalizado.Frete = Convert.ToDouble(GetFretePrazo(pedNaoFinalizado)["Frete"]);

            if (naoTemPedido)
                pedNaoFinalizado.CartaoPedidos = new List<CartaoPedido>
                {
                    new CartaoPedido
                    {
                        Cartao = clienteDb.Cartoes.Where(c => c.EFavorito && !c.Inativo).FirstOrDefault(),
                        Pedido = pedNaoFinalizado,
                        Valor = carrinho.PrecoTotal()
                    }
                };

            if (naoTemPedido)
                clienteDb.Pedidos.Add(pedNaoFinalizado);


            _facade.Editar(clienteDb);

            //PREPARAÇÃO DO VIEWMODEL

            IDictionary<CartaoCredito, double> dicCartoes = new Dictionary<CartaoCredito, double>();
            foreach (var item in pedNaoFinalizado.CartaoPedidos)
                dicCartoes[item.Cartao] = item.Valor;

            IDictionary<string, object> entidades = new Dictionary<string, object>
            {
                [typeof(Endereco).Name] = pedNaoFinalizado.Endereco,
                [typeof(IDictionary<CartaoCredito, double>).Name] = dicCartoes,
                [typeof(Carrinho).Name] = carrinho,
                [nameof(Pedido.Frete)] = pedNaoFinalizado.Frete
            };
            if (pedNaoFinalizado.Cupom != null)
                entidades[typeof(Cupom).Name] = pedNaoFinalizado.Cupom;
            if (pedNaoFinalizado.CodigoPromocional != null)
                entidades[typeof(CodigoPromocional).Name] = pedNaoFinalizado.CodigoPromocional;

            _vh = new PaginaFinalizarCompraViewHelper
            {
                Entidades = entidades
            };

            ViewData["FinalizarCompra"] = true;
            if (!String.IsNullOrEmpty((string)TempData["Alert"])) ViewData["Alert"] = TempData["Alert"];

            return View(_vh.ViewModel); 
        }

        public IActionResult Comprar()
        {
            Cliente clienteDb = GetClienteDb();
            Pedido p = GetPedidoNaoFinalizado(clienteDb);
            Carrinho c = GetCarrinho();

            if (p == null)
            {
                TempData["Alert"] = "Ocorreu um erro. Tente novamente\n.";
                return RedirectToAction(nameof(FinalizarCompra));
            }

            IEnumerable<Livro> livros = p.LivrosPedidos.Select(l => l.Livro).Distinct();

            p.ValorTotal = p.CalcularValorTotal();

            if(p.Cupom != null || p.CodigoPromocional != null)
            {
                Cupom cupom = p.Cupom ?? new Cupom { Valor = 0 };
                CodigoPromocional codigo = p.CodigoPromocional ?? new CodigoPromocional { Valor = 0};

                if(cupom.Valor + codigo.Valor >= p.ValorTotal)
                {
                    foreach(var cupomCliente in clienteDb.Cupons)
                    {
                        if (cupomCliente.Valor + codigo.Valor < p.ValorTotal) 
                        {
                            TempData["Alert"] = "Você possui um cupom de troca que não ultrapassa o valor máximo. Use ele ao invés do atual!\n.";
                            return RedirectToAction(nameof(FinalizarCompra));
                        }
                    }
                    var diferenca = cupom.Valor + codigo.Valor - p.ValorTotal;
                    if(diferenca > 0)
                    {
                        addCupom(clienteDb, diferenca);
                    }
                }
            }

            //Cupom
            if (p.Cupom != null)
            { 
                p.Cupom.Inativo = true;
            }

            //Codigo
            if(p.CodigoPromocional != null)
            {
                p.CodigoPromocional.UsosRestantes -= 1;
                if(p.CodigoPromocional.UsosRestantes == 0)
                {
                    p.CodigoPromocional.Inativo = true;
                }
            }

            //Atualização estoque
            foreach (var livro in livros)
            {
                var quantiaPedido = p.LivrosPedidos.Where(l => l.LivroId == livro.Id).Count();
                livro.EstoqueBloqueado -= quantiaPedido;
                livro.Estoque -= quantiaPedido;

                //Inativação Automática de Livros fora de estoque
                if (livro.Estoque <= 0) 
                { 
                    livro.Inativo = true;
                    livro.Inativacoes.Add(new Inativacao { CategoriaId = 1, LivroId = livro.Id });
                }
            }

            p.Status = StatusPedidos.Processamento;
            string msg = _facade.Editar(p);

            //Limpar Carrinho (feito decrescente pois estou removendo da lista)
            msg += _facade.Deletar(c);

            if (msg != "")
                TempData["Alert"] = msg;
            return RedirectToAction("Loja", "Livros");
        }

        #region Selecionar Endereco e Cartao

        public IActionResult _SelecionarEndereco()
        {
            Cliente clienteDb = GetClienteDb();

            _vh = new SelecionarEnderecoViewHelper
            {
                Entidades = new Dictionary<string, object>
                {
                    [typeof(IList<Endereco>).Name] = clienteDb.Enderecos
                }
            };

            SelecionarEnderecoModel vm = (SelecionarEnderecoModel)_vh.ViewModel;
            vm.TiposEnderecos = _facade.Listar<TipoEndereco>().OrderBy(t => t.Nome).ToList();
            vm.EnderecoId = GetPedidoNaoFinalizado(clienteDb).EnderecoId;

            return PartialView("../CarrinhoCompra/PartialViews/_SelecionarEndereçoPartial", vm);
        }

        [HttpPost]
        public IActionResult AlterarEndereco(SelecionarEnderecoModel vm)
        {
            _vh = new SelecionarEnderecoViewHelper
            {
                ViewModel = vm
            };

            int id = ((Endereco)_vh.Entidades[typeof(Endereco).Name]).Id;
            Cliente clienteDb = GetClienteDb();
            Endereco e = clienteDb.Enderecos.Where(e => e.Id == id).FirstOrDefault();
            Pedido p = GetPedidoNaoFinalizado(clienteDb);

            p.Endereco = e;
            string msg = _facade.Editar(p);

            if (msg != "")
                TempData["Alert"] = msg;
            return RedirectToAction(nameof(FinalizarCompra));
        }

        public IActionResult _SelecionarCartao()
        {
            Cliente clienteDb = GetClienteDb();
            Pedido p = GetPedidoNaoFinalizado(clienteDb);
            IList<CartaoPedido> cartaoPedido = p.CartaoPedidos;
            IList<CartaoCredito> cartoes = clienteDb.Cartoes;

            _vh = new SelecionarCartaoViewHelper
            {
                Entidades = new Dictionary<string, object>
                {
                    ["CartaoPedio"] = cartaoPedido,
                    [typeof(IList<CartaoCredito>).Name] = cartoes
                }
            };
            SelecionarCartaoModel vm = (SelecionarCartaoModel)_vh.ViewModel;
            vm.Bandeiras = _facade.Listar<BandeiraCartaoCredito>().OrderBy(b => b.Nome).ToList();
            vm.Vencimento = DateTime.Now;

LES/LES/Controllers/ImagemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LES.Controllers.Facade;
using LES.Models.Entity;
using Microsoft.AspNetCore.Mvc;

namespace LES.Controllers
{
    public class ImagemController : Controller
    {
        IFacadeCrud _facade { get; set; }

        public ImagemController(IFacadeCrud facade)
        {
            _facade = facade;
        }

        public IActionResult Livro(string codBar)
        {
            byte[] img = _facade.Query<Livro>(l => l.CodigoBarras == codBar,
                l => l).FirstOrDefault().Capa;

            return File(img, "image/png");
        }

    }
}

LES/LES/Controllers/LivrosController.cs
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Threading.Tasks;
using LES.Controllers.Facade;
using LES.Models.Entity;
using LES.Models.ViewHelpers.Livros;
using LES.Models.ViewHelpers.Shared;
using LES.Models.ViewModel.Livros;
using LES.Models.ViewModel.Shared;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Query.Internal;
using Newtonsoft.Json.Linq;

namespace LES.Controllers
{
    public class LivrosController : BaseController
    {
        
        IFacadeCrud _facade { get; set; }

        public LivrosController(IFacadeCrud facade)
        {
            _facade = facade;
        }

        public IActionResult Loja()
        {
            IList<Livro> livros = _facade.ListAllInclude<Livro>().OrderBy(l => l.Titulo).Where(l => !l.Inativo).ToList();

            _vh = new PaginaLojaViewHelper 
            {
                Entidades = new Dictionary<string, object>
                {
                    [typeof(IList<Livro>).Name] = livros.Take(8).ToList(),
                    [nameof(ListaCardLivrosModel.PagMax)] = (livros.Count / 10) + 1,
                    [nameof(ListaCardLivrosModel.PagAtual)] = 1
                }
            };

            if (TempData["Alert"] != null)
                ViewData["Alert"] = (string)TempData["Alert"];

            return View(_vh.ViewModel);
        }

        [HttpPost]
        public IActionResult Pesquisa(string filtro) 
        {

            JObject o = JObject.Parse(filtro);

            LojaFiltrosModel filtros = o.ToObject<LojaFiltrosModel>();

            IEnumerable<Livro> livros = _facade.ListAllInclude<Livro>()
                .Where(l => !l.Inativo)
                .OrderBy(l => l.Titulo);

            if (!String.IsNullOrEmpty(filtros.Titulo))
                livros = livros.Where(l => l.Titulo.Contains(filtros.Titulo));

            if (!String.IsNullOrEmpty(filtros.Autor))
                livros = livros.Where(l => l.Autor.Contains(filtros.Autor));

            if (!String.IsNullOrEmpty(filtros.Isbn))
                livros = livros.Where(l => l.Isbn.Contains(filtros.Isbn));

            if (!String.IsNullOrEmpty(filtros.Editora))
                livros = livros.Where(l => l.Editora.Nome.Contains(filtros.Editora));

            if (!String.IsNullOrEmpty(filtros.Categorias)) 
            {
                string[] ctgs = filtros.Categorias.Split(" ");
                IEnumerable<CategoriaLivro> categoriaLivros = _facade.Query<CategoriaLivro>(c => ctgs.Contains(c.Nome),
                    c => c);

                IEnumerable<LivroCategoriaLivro> livCtl = livros.SelectMany(c => c.LivrosCategoriaLivros);

                IEnumerable<int> ids = livCtl.Where(l => categoriaLivros.Select(c => c.Id).Contains(l.CategoriaLivroId))
                    .Select(l => l.LivroId).Distinct();

                livros = livros.Where(l => ids.Contains(l.Id));
            }

            if (filtros.PrecoMin > 0)
                livros = livros.Where(l => l.Valor > filtros.PrecoMin);

            if (filtros.PrecoMax > 0)
                livros = livros.Where(l => l.Valor < filtros.PrecoMax);

            if (!String.IsNullOrEmpty(filtros.DataMin)) 
            {
                DateTime dataMin = Convert.ToDateTime(filtros.DataMin);
                livros = livros.Where(l => l.DtLancamento.Date >= dataMin.Date);
            }

            if (!String.IsNullOrEmpty(filtros.DataMax))
            {
                DateTime dataMax = Convert.ToDateTime(filtros.DataMax);
                livros = livros.Where(l => l.DtLancamento.Date <= dataMax.Date);
            }

            if (filtros.PaginaAtual > 0)
                livros = livros.Skip((filtros.PaginaAtual - 1) * 8);

            _vh = new ListaCardLivrosViewHelper
            {
                Entidades = new Dictionary<string, object>
                {
                    [typeof(IList<Livro>).Name] = livros.Take(8).ToList(),
                    [nameof(ListaCardLivrosModel.PagAtual)] = filtros.PaginaAtual,
                    [nameof(ListaCardLivrosModel.PagMax)] = (livros.Count() / 8) + 1
                }
            };

            return PartialView("../Shared/_ListaLivrosCardPartial", _vh.ViewModel);
        }

        public IActionResult Descricao(string codBar)
        {
            Livro livro = _facade.GetAllInclude(new Livro { CodigoBarras = codBar });

            _vh = new LivroBaseViewHelper
            {
                Entidades = new Dictionary<string, object>
                {
                    [typeof(Livro).Name] = livro
                }
            };

            return View(_vh.ViewModel);
        }
    }
}

LES/LES/Views/Livros/Descricao.cshtml
@model LES.Models.ViewModel.Shared.LivroBaseModel

@{
    ViewData["Title"] = "Descrição";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<div class="container ">
    <div class="row">
        <div class="col-4 text-center pr-3 border-right border-secondary">
            <img src="@Url.Action("Livro", "Imagem")?codBar=@(Model.CodigoBarras)" class="img-fluid" />
        </div>
        <div class="col-7 mt-lg-3">
            <div class="container">
                <div class="row">
                    <div class="col-12 align-content-lg-start font-weight-light">
                        <h3>@Model.Titulo</h3>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-8 align-content-lg-start border-bottom">
                        <h4 class="font-weight-light">@Model.Autor</h4>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 text-justify border-bottom mb-2">
                        @Model.Sinopse
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-12 font-weight-light text-center border-bottom">
                        <h4>Ficha Técnica</h4>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-sm-4">
                        <div class="row">
                            <span class="col-sm-12 font-weight-bold text-center">Editora</span>
                        </div>
                        <div class="row">
                            <span class="col-sm-12 font-weight-light text-center">@Model.Editora</span>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="row">
                            <span class="col-sm-12 font-weight-bold text-center">Ano de lançamento</span>
                        </div>
                        <div class="row">
                            <span class="col-sm-12 font-weight-light text-center">@Model.DtLancamento.Year</span>
                        </div>
                    </div>
                    <div class="col-sm-4 ">
                        <div class="row">
                            <span class="col-sm-12 font-weight-bold text-center">Páginas</span>
                        </div>
                        <div class="row">
                            <span class="col-sm-12 font-weight-light text-center">@Model.Paginas</span>
                        </div>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-lg-3">
                        <div class="row">
                            <span class="col-sm-12 font-weight-bold text-center">Edição</span>
                        </div>
                        <div class="row">
                            <span class="col-sm-12 font-weight-light text-center">@Model.Edicao</span>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="row">
                            <span class="col-sm-12 font-weight-bold text-center">Largura</span>
                        </div>
                        <div class="row">
                            <span class="col-sm-12 font-weight-light text-center">@Model.Largura</span>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="row">
                            <span class="col-sm-12 font-weight-bold text-center">Comprimento</span>
                        </div>
                        <div class="row">
                            <span class="col-sm-12 font-weight-light text-center">@Model.Comprimento</span>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="row">
                            <span class="col-sm-12 font-weight-bold text-center">Altura</span>
                        </div>
                        <div class="row">
                            <span class="col-sm-12 font-weight-light text-center">@Model.Altura</span>
                        </div>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-sm-8 align-content-lg-end text-center my-4">
                        <h2 class="font-weight-bold">R$ @Model.Preco.ToString("0.00").Replace('.', ',')</h2>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-8 font-weight-bold text-center">
                        <span class="text-center">
                            Categorias
                        </span>
                    </div>
                </div>
                <div class="row justify-content-center">
                    @foreach (var item in Model.Categorias)
                    {
                        <span class="border rounded bg-light text-dark p-1 mb-2 mx-3"><small>@item</small></span>
                    }
                </div>
                <div class="row justify-content-end">
                    <div class="col-8"></div>
                    <span class="col-1"> x </span>
                    <div class="col-3 justify-content-end">
                        <input class="form-control mr-1" type="number" min="1" value="1" id="QuantiaItens" />
                    </div>
                </div>
                <div class="row justify-content-center">
                    <button type="button" class="btn btn-success col-sm-7 mr-4 text-center comprarAgora" value="@Model.CodigoBarras">COMPRAR AGORA</button>
                    <button type="button" class="btn btn-outline-success col-sm-4 text-center addtoCarrinho" value="@Model.CodigoBarras"><small><i class="fa fa-shopping-cart"></i></small></button>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        var urls = urls || {};
        urls.AddCarrinho = '@Url.Action("_AddToCarrinho", "CarrinhoCompra")';
        urls.FinalizarCompra = '@Url.Action("FinalizarCompra","CarrinhoCompra")';
    </script>
    <script src="~/js/Shared/AddToCarrinho.js"></script>
    <script src="~/js/Carrinho/ComprarAgora.js"></script>

}

LES/LES/Views/Livros/Loja.cshtml
@model LES.Models.ViewModel.Livros.PaginaLojaModel

@{
    ViewData["Title"] = "SóRaiva Livros";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row no-gutters">
    <div class="container-fluid">
        <div class="row">
            <div id="sidebar" class="col-md-3 sticky-top border-right" style="height:6rem; top:10%">
                <partial name="../Livros/PartialViews/_LojaFiltroSidebarPartial.cshtml" for="Filtros">
            </div>
            <div id="divLoja" class="col-md-9 div-loja">
                <partial name="../Shared/_ListaLivrosCardPartial.cshtml" for="Livros">
            </div>
        </div>
    </div>

</div>

@section Scripts{

    <script type="text/javascript">
        var urls = urls || {};
        urls.Pesquisar = '@Url.Action("Pesquisa", "Livros")';
        urls.AddCarrinho = '@Url.Action("_AddToCarrinho", "CarrinhoCompra")';
    </script>
    <script src="~/js/Shared/AddToCarrinho.js"></script>
    <script src="~/js/Livros/CarregarPesquisa.js"></script>
}