LES/LES/Models/ViewHelpers/Shared/ListaCardLivrosViewHelper.cs
using LES.Models.Entity;
using LES.Models.ViewModel.Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LES.Models.ViewHelpers.Shared
{
    public class ListaCardLivrosViewHelper : AbstractViewHelper, IViewHelper
    {
        protected override void ToEntidade()
        {
            throw new NotImplementedException();
        }

        protected override void ToViewModel()
        {
            ListaCardLivrosModel vm = new ListaCardLivrosModel();

            LivroBaseViewHelper livCarHelper = new LivroBaseViewHelper();

            IList<Livro> livros;

            if (Entidades == null)
            {
                _viewModel = vm;
                return;
            }

            if (Entidades.ContainsKey(typeof(IList<Livro>).Name))
            {
                livros = (IList<Livro>)Entidades[typeof(IList<Livro>).Name];

                foreach (var l in livros)
                {
                    livCarHelper.Entidades = new Dictionary<string, object>
                    {
                        [typeof(Livro).Name] = l
                    };

                    vm.Livros.Add((LivroBaseModel)livCarHelper.ViewModel);
                }
            }

            string pagAtual = nameof(ListaCardLivrosModel.PagAtual),
                pagMax = nameof(ListaCardLivrosModel.PagMax);

            if (Entidades.ContainsKey(pagAtual))
                vm.PagAtual = (int)Entidades[pagAtual];
            else
                vm.PagAtual = 1;

            if (Entidades.ContainsKey(pagMax))
                vm.PagMax = (int)Entidades[pagMax];

            _viewModel = vm;
        }
    }
}

LES/LES/Models/ViewModel/Shared/ListaCardLivrosModel.cs
using Microsoft.AspNetCore.Mvc.ViewEngines;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LES.Models.ViewModel.Shared
{
    public class ListaCardLivrosModel : IViewModel
    {
        public IList<LivroBaseModel> Livros { get; set; } = new List<LivroBaseModel>();

        public int PagAtual { get; set; }

        public int PagMax { get; set; }


    }
}

LES/LES/Controllers/AdminController.cs
using LES.Controllers.Facade;
using LES.Data.DAO;
using LES.Models.Entity;
using LES.Models.ViewHelpers.Admin;
using LES.Models.ViewModel.Admin;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;

namespace LES.Controllers
{
    [Authorize(Roles = "1,2")]
    public class AdminController : BaseController
    {
        IFacadeCrud _facade { get; set; }

        public AdminController(
            IFacadeCrud facade)
        {
            _facade = facade;
        }

        public IActionResult Home()
        {
            return View(new PaginaAdminHomeModel());
        }

        public IActionResult Clientes()
        {
            IEnumerable<Cliente> clientes = _facade.ListAllInclude<Cliente>()
            .Where(c => !c.Inativo);

            _vh = new PaginaClientesViewHelper
            {
                Entidades = new Dictionary<string, object>
                {
                    [typeof(IList<Cliente>).FullName] = clientes.Take(10).ToList(),
                    [nameof(ListaClientesModel.PagAtual)] = 1,
                    [nameof(ListaClientesModel.PagMax)] = (clientes.Count() / 10) + 1
                }
            };

            if (TempData["Alert"] != null) ViewData["Alert"] = TempData["Alert"];

            return View(_vh.ViewModel);
        }

        public IActionResult Pedidos()
        {
            IEnumerable<Pedido> pedidos = _facade.ListAllInclude<Pedido>()
                .Where(p => p.Status != StatusPedidos.NaoFinalizado && !p.Inativo);

            IEnumerable<Troca> trocas = _facade.ListAllInclude<Troca>();

            _vh = new PaginaPedidosViewHelper 
            {
                Entidades = new Dictionary<string, object>
                {
                    [typeof(IList<Pedido>).FullName] = pedidos.Take(10).ToList(),
                    [nameof(ListaPedidosAdminModel.PagAtual)] = 1,
                    [nameof(ListaPedidosAdminModel.PagMax)] = (pedidos.Count() / 10) + 1,
                    [typeof(IList<Troca>).FullName] = trocas.Take(10).ToList(),
                    [nameof(ListaTrocasAdminModel.PagAtual)] = 1,
                    [nameof(ListaTrocasAdminModel.PagMax)] = (trocas.Count() / 10) + 1
                }
            };

            if (TempData["Alert"] != null) ViewData["Alert"] = TempData["Alert"];

            return View(_vh.ViewModel);
        }

        public IActionResult ConfigLoja() {
            IList<Livro> livros = _facade.ListAllInclude<Livro>().Where(l => !l.Inativo).ToList();
            IList<CategoriaLivro> categorias = _facade.Listar<CategoriaLivro>().Where(c => !c.Inativo).ToList();
            IList<GrupoPreco> grupos = _facade.Listar<GrupoPreco>().Where(c => !c.Inativo).ToList();
            IList<CodigoPromocional> codigos = _facade.Listar<CodigoPromocional>().Where(c => !c.Inativo).ToList();

            _vh = new PaginaConfigLojaViewHelper
            {
                Entidades = new Dictionary<string, object>
                {
                    [typeof(IList<Livro>).FullName] = livros,
                    [typeof(IList<CategoriaLivro>).FullName] = categorias,
                    [typeof(IList<GrupoPreco>).FullName] = grupos,
                    [typeof(IList<CodigoPromocional>).FullName] = codigos
                }
            };
            if (TempData["Alert"] != null) ViewData["Alert"] = TempData["Alert"];

            return View(_vh.ViewModel);
        }

        #region Pedidos

        [HttpPost]

        public IActionResult _PedidosBusca(string filtro)
        {
            JObject o = JObject.Parse(filtro);

            FiltrosPedidosAdminModel filtros = o.ToObject<FiltrosPedidosAdminModel>();

            IEnumerable<Pedido> pedidos = _facade.ListAllInclude<Pedido>()
                .Where(p => p.Status != StatusPedidos.NaoFinalizado && !p.Inativo);

            if (filtros.Id.HasValue)
                if (filtros.Id > 0)
                    pedidos = pedidos.Where(p => p.Id == filtros.Id);

            if (!String.IsNullOrEmpty(filtros.Nome))
                pedidos = pedidos.Where(p => p.Cliente.Nome.Contains(filtros.Nome));

            if (filtros.DtMin != null && filtros.DtMin != new DateTime())
                pedidos = pedidos.Where(p => p.DtCadastro > filtros.DtMin);

            if (filtros.DtMax != null && filtros.DtMax != new DateTime())
                pedidos = pedidos.Where(p => p.DtCadastro < filtros.DtMax);

            if (filtros.ValorMin > 0)
                pedidos = pedidos.Where(p => p.ValorTotal > filtros.ValorMin);

            if (filtros.ValorMax > 0)
                pedidos = pedidos.Where(p => p.ValorTotal < filtros.ValorMax);

            pedidos = !String.IsNullOrEmpty(filtros.Status) ?
                pedidos.Where(p => p.Status == (StatusPedidos)Convert.ToInt32(filtros.Status)) : pedidos;

            if (filtros.PagAtual > 0)
                pedidos = pedidos.Skip((filtros.PagAtual - 1) * 10);

            _vh = new PaginaPedidosViewHelper
            {
                Entidades = new Dictionary<string, object>
                {
                    [typeof(IList<Pedido>).FullName] = pedidos.Take(10).ToList(),
                    [nameof(ListaPedidosAdminModel.PagAtual)] = 1,
                    [nameof(ListaPedidosAdminModel.PagMax)] = (pedidos.Count() / 10) + 1
                }
            };

            PaginaPedidosModel vm = (PaginaPedidosModel)_vh.ViewModel;
            vm.Filtros = filtros;

            return PartialView("../Admin/PartialViews/_TabelaPedidosPartial", vm);
        }
        public IActionResult _VisualizarPedidoPartial(int id)
        {
            _vh = new AdminPedidoViewHelper
            {
                Entidades = new Dictionary<string, object>
                {
                    [typeof(Pedido).Name] = _facade.GetAllInclude(new Pedido { Id = id })
                }
            };
            return PartialView("../Admin/PartialViews/_VisualizarPedidoPartial", _vh.ViewModel);
        }

        [HttpPost]
        public IActionResult StatusPedido(AdminPedidoModel pedido)
        {
            Pedido p = _facade.GetAllInclude(new Pedido { Id = Convert.ToInt32(pedido.Id) });
            p.Status = pedido.Status;

            string msg = _facade.Editar(p);

            if (msg != "")
                TempData["Alert"] = msg;
            return RedirectToAction(nameof(Pedidos));
        }

        #endregion

        #region Troca    

        [HttpPost]
        public IActionResult _TrocasBusca(string filtro)
        {
            JObject o = JObject.Parse(filtro);

            FiltrosPedidosAdminModel filtros = o.ToObject<FiltrosPedidosAdminModel>();

            IEnumerable<Troca> trocas = _facade.ListAllInclude<Troca>();

            trocas = filtros.Id != null ? trocas.Where(t => t.Id == filtros.Id) : trocas;

            trocas = !String.IsNullOrEmpty(filtros.Nome) ? 
                trocas.Where(t => t.Cliente.Nome.Contains(filtros.Nome)) : trocas;

            trocas = (filtros.DtMin != null && filtros.DtMin != new DateTime()) ? 
                trocas.Where(t => t.DtCadastro > filtros.DtMin) : trocas;

            trocas = (filtros.DtMax != null && filtros.DtMax != new DateTime()) ? 
                trocas.Where(t => t.DtCadastro < filtros.DtMax ) : trocas;

            trocas = filtros.ValorMin > 0 ? 
                trocas.Where(t => t.LivroPedido.Livro.Valor > filtros.ValorMin) : trocas;

            trocas = filtros.ValorMax > 0 ? 
                trocas.Where(t => t.LivroPedido.Livro.Valor < filtros.ValorMax) : trocas;

            trocas = !String.IsNullOrEmpty(filtros.Status) ?
                trocas.Where(p => p.StatusTroca == (StatusTroca)Convert.ToInt32(filtros.Status)) : trocas;

            trocas = filtros.PagAtual > 0 ? trocas.Skip((filtros.PagAtual - 1) * 10) : trocas;

            _vh = new PaginaPedidosViewHelper
            {
                Entidades = new Dictionary<string, object>
                {
                    [typeof(IList<Troca>).FullName] = trocas.Take(10).ToList(),
                    [nameof(ListaTrocasAdminModel.PagAtual)] = 1,
                    [nameof(ListaTrocasAdminModel.PagMax)] = (trocas.Count() / 10) + 1
                }
            };

            PaginaPedidosModel vm = (PaginaPedidosModel)_vh.ViewModel;
            vm.Filtros = filtros;

            return PartialView("../Admin/PartialViews/_TabelaTrocasPartial", vm);
        }

        public IActionResult _VisualizarTrocaPartial(int id)
        {
            _vh = new AdminTrocaViewHelper
            {
                Entidades = new Dictionary<string, object>
                {
                    [typeof(Troca).Name] = _facade.GetAllInclude(new Troca { Id = id })
                }
            };
            return PartialView("../Admin/PartialViews/_VisualizarTrocaPartial", _vh.ViewModel);
        }

        [HttpPost]
        public IActionResult StatusTroca(AdminTrocaModel troca)
        {
            Troca t = _facade.GetAllInclude(new Troca { Id = troca.Id });
            t.StatusTroca = troca.Status;
            Cliente c = null;
            if (t.StatusTroca == Models.Entity.StatusTroca.Trocada)
            {
                c = _facade.GetAllInclude(t.Cliente);
                addCupom(c, t.LivroPedido);
            }

            string msg = _facade.Editar(t);
            if (c != null)
                msg += _facade.Editar(c);

            if (msg != "")
                TempData["Alert"] = msg;
            return RedirectToAction(nameof(Pedidos));
        }

        #endregion

        #region Clientes


        [HttpPost]

        public IActionResult _ClientesBusca(string filtro)
        {
            JObject o = JObject.Parse(filtro);

            FiltrosClientesModel filtros = o.ToObject<FiltrosClientesModel>();

LES/LES/Controllers/ImagemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LES.Controllers.Facade;
using LES.Models.Entity;
using Microsoft.AspNetCore.Mvc;

namespace LES.Controllers
{
    public class ImagemController : Controller
    {
        IFacadeCrud _facade { get; set; }

        public ImagemController(IFacadeCrud facade)
        {
            _facade = facade;
        }

        public IActionResult Livro(string codBar)
        {
            byte[] img = _facade.Query<Livro>(l => l.CodigoBarras == codBar,
                l => l).FirstOrDefault().Capa;

            return File(img, "image/png");
        }

    }
}

LES/LES/Controllers/LivrosController.cs
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Threading.Tasks;
using LES.Controllers.Facade;
using LES.Models.Entity;
using LES.Models.ViewHelpers.Livros;
using LES.Models.ViewHelpers.Shared;
using LES.Models.ViewModel.Livros;
using LES.Models.ViewModel.Shared;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Query.Internal;
using Newtonsoft.Json.Linq;

namespace LES.Controllers
{
    public class LivrosController : BaseController
    {
        
        IFacadeCrud _facade { get; set; }

        public LivrosController(IFacadeCrud facade)
        {
            _facade = facade;
        }

        public IActionResult Loja()
        {
            IList<Livro> livros = _facade.ListAllInclude<Livro>().OrderBy(l => l.Titulo).Where(l => !l.Inativo).ToList();

            _vh = new PaginaLojaViewHelper 
            {
                Entidades = new Dictionary<string, object>
                {
                    [typeof(IList<Livro>).Name] = livros.Take(8).ToList(),
                    [nameof(ListaCardLivrosModel.PagMax)] = (livros.Count / 10) + 1,
                    [nameof(ListaCardLivrosModel.PagAtual)] = 1
                }
            };

            if (TempData["Alert"] != null)
                ViewData["Alert"] = (string)TempData["Alert"];

            return View(_vh.ViewModel);
        }

        [HttpPost]
        public IActionResult Pesquisa(string filtro) 
        {

            JObject o = JObject.Parse(filtro);

            LojaFiltrosModel filtros = o.ToObject<LojaFiltrosModel>();

            IEnumerable<Livro> livros = _facade.ListAllInclude<Livro>()
                .Where(l => !l.Inativo)
                .OrderBy(l => l.Titulo);

            if (!String.IsNullOrEmpty(filtros.Titulo))
                livros = livros.Where(l => l.Titulo.Contains(filtros.Titulo));

            if (!String.IsNullOrEmpty(filtros.Autor))
                livros = livros.Where(l => l.Autor.Contains(filtros.Autor));

            if (!String.IsNullOrEmpty(filtros.Isbn))
                livros = livros.Where(l => l.Isbn.Contains(filtros.Isbn));

            if (!String.IsNullOrEmpty(filtros.Editora))
                livros = livros.Where(l => l.Editora.Nome.Contains(filtros.Editora));

            if (!String.IsNullOrEmpty(filtros.Categorias)) 
            {
                string[] ctgs = filtros.Categorias.Split(" ");
                IEnumerable<CategoriaLivro> categoriaLivros = _facade.Query<CategoriaLivro>(c => ctgs.Contains(c.Nome),
                    c => c);

                IEnumerable<LivroCategoriaLivro> livCtl = livros.SelectMany(c => c.LivrosCategoriaLivros);

                IEnumerable<int> ids = livCtl.Where(l => categoriaLivros.Select(c => c.Id).Contains(l.CategoriaLivroId))
                    .Select(l => l.LivroId).Distinct();

                livros = livros.Where(l => ids.Contains(l.Id));
            }

            if (filtros.PrecoMin > 0)
                livros = livros.Where(l => l.Valor > filtros.PrecoMin);

            if (filtros.PrecoMax > 0)
                livros = livros.Where(l => l.Valor < filtros.PrecoMax);

            if (!String.IsNullOrEmpty(filtros.DataMin)) 
            {
                DateTime dataMin = Convert.ToDateTime(filtros.DataMin);
                livros = livros.Where(l => l.DtLancamento.Date >= dataMin.Date);
            }

            if (!String.IsNullOrEmpty(filtros.DataMax))
            {
                DateTime dataMax = Convert.ToDateTime(filtros.DataMax);
                livros = livros.Where(l => l.DtLancamento.Date <= dataMax.Date);
            }

            if (filtros.PaginaAtual > 0)
                livros = livros.Skip((filtros.PaginaAtual - 1) * 8);

            _vh = new ListaCardLivrosViewHelper
            {
                Entidades = new Dictionary<string, object>
                {
                    [typeof(IList<Livro>).Name] = livros.Take(8).ToList(),
                    [nameof(ListaCardLivrosModel.PagAtual)] = filtros.PaginaAtual,
                    [nameof(ListaCardLivrosModel.PagMax)] = (livros.Count() / 8) + 1
                }
            };

            return PartialView("../Shared/_ListaLivrosCardPartial", _vh.ViewModel);
        }

        public IActionResult Descricao(string codBar)
        {
            Livro livro = _facade.GetAllInclude(new Livro { CodigoBarras = codBar });

            _vh = new LivroBaseViewHelper
            {
                Entidades = new Dictionary<string, object>
                {
                    [typeof(Livro).Name] = livro
                }
            };

            return View(_vh.ViewModel);
        }
    }
}

LES/LES/Views/Shared/_CarrinhoPartial.cshtml
@model LES.Models.ViewModel.Carrinho.CarrinhoModel

    <form>
        <div class="container dropdown-item">
            <div class="row">
                <h4 class="font-weight-light">Carrinho de compras</h4>
            </div>
            <div id="alertCarrinho"></div>
                <table class="table table-borderless row">
                    <tbody>
                        @foreach (var item in Model.Livros)
                        { 
                            <tr class="form-group">
                                <partial name="_ItemCarrinhoPartial" for="@item">
                            </tr> 
                        }
                    </tbody>
                </table>
        </div>
        <div class="dropdown-divider"></div>
        <div class="container">
            <div class="row justify-content-end mx-3">
                <h6 class="text-muted col-4">Preço:</h6><h5 class="text-left col-3">R$ @Model.PrecoTotal.ToString("0.00")</h5>
            </div>
            <div class="row justify-content-center">
                <button type="button" class="btn btn-outline-success btn-carrinho-comprar col-11" onclick="window.location.href='@Url.Action("FinalizarCompra","CarrinhoCompra")'" style="font-size:0.75rem">Confirmar compra</button>
            </div>
        </div>
    </form>

LES/LES/Views/Shared/_ItemCarrinhoPartial.cshtml
@model LES.Models.ViewModel.Carrinho.CarrinhoLivroModel

    <td>
        <img src="@Url.Action("Livro","Imagem")?codBar=@Model.CodigoBarras" class="capa-carrinho" style="z-index:101"/>
    </td>
    <td style="width:30%">
        <div class=""><h6>@Model.Titulo</h6></div>
        <div class="font-weight-lighter"><h6>@Model.Autor</h6></div>
    </td>
    <td>
        <div class=""><small>R$ @Model.Preco.ToString("0.00")</small></div>
        <div class="font-weight-lighter"><h4>x @Model.Quantia</h4></div>
    </td>
    <td>
        <button type="button" class="btn btn-light mais-carrinho" value="@Model.CodigoBarras"style="z-index:101">+</button>
        <button type="button" class="btn btn-light menos-carrinho" value="@Model.CodigoBarras"style="z-index:101">-</button>
    </td>
    <td>
        <button type="button" class="btn btn-danger remover-carrinho" value="@Model.CodigoBarras"style="z-index:101">&times;</button>
    </td>

LES/LES/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SóRaiva</title>
    <link href="~/css/Shared/Normalize.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous" />
</head>
<body>
    <header>

        <nav class=" navbar navbar-dark navbar-toggleable-sm navbar-expand-xl fixed-top box-shadow mb-3 navbar-verde">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SóRaiva</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div id="navbarSupportedContent" class="collapse navbar-collapse flex-sm-row-reverse">
                    <ul class="navbar-nav">
                        <partial name="_ContaPartial" />
                    </ul>
                    @if (User.IsInRole("1") || User.IsInRole("2"))
                    {
                        <ul class="navbar-nav">
                            <li>
                                <a class="btn btn-dark nav-link navbar-item" asp-action="Home" asp-controller="Admin">Área do Admin</a>
                            </li>
                        </ul>
                    }
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link navbar-item" asp-action="Loja" asp-controller="Livros">Livros</a>
                        </li>
                        @if (User.Identity.IsAuthenticated && ViewData["FinalizarCompra"] == null)
                        {
                            <li class="nav-item">
                                <div class="dropdown dropright">
                                    <a class="nav-link dropdown-toggle navbar-item carrinho-update" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Carrinho
                                    </a>
                                    <div id="dropdown" class="dropdown-menu" aria-labelledby="navbarDropdown" style="max-width:600px;z-index:100"></div>
                                </div>
                            </li>
                        }
                    </ul>
                    <!--<ul class="navbar-nav">
                        <li class="nav-item">
                            <form class="form-inline my-2 my-lg-0">
                                <input class="form-control mr-sm-2" type="Pesquisar" placeholder="Pesquisar" aria-label="Pesquisar">
                                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Pesquisar</button>
                            </form>
                        </li>
                    </ul>-->
                </div>
            </div>
        </nav>

    </header>
    <div class="container renderedBody">
        <main role="main" class="pb-3">

            <div class="row" id="alertRow">
                @if (ViewData["Alert"] != null)
                {
                    <div class="col-sm-12">
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <strong>ERRO</strong>
                            @(ViewData["Alert"])
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    </div>
                }
            </div>

            @RenderBody()
        </main>
    </div>

    <!--<footer class="footer">
        <div class="container text-footer align-content-lg-start">
            &copy; 2021 - LES - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>-->

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript">
        var carrinhoUrl = '@Url.Action("_CarrinhoPartial", "CarrinhoCompra")';
        var carrinhoMais = '@Url.Action("_MaisQuantiaNoCarrinho", "CarrinhoCompra")';
        var carrinhoMenos = '@Url.Action("_MenosQuantiaNoCarrinho", "CarrinhoCompra")';
        var carrinhoRemover = '@Url.Action("_RemoverDoCarrinho", "CarrinhoCompra")';
    </script>
    <script src="~/js/Shared/Carrinho.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

LES/LES/Views/Shared/_LivroCardPartial.cshtml
@model LES.Models.ViewModel.Shared.LivroBaseModel

@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

    <div class="col-md-3">
        <div class="card mb-3">
            <div class="align-items-center p-2 text-center">
                <img src="@Url.Action("Livro","Imagem")?codBar=@(Model.CodigoBarras)" style="max-height:200px"/>
                <h5 class="font-weight-light">@(Model.Titulo)</h5>
                <h6>@(Model.Autor)</h6>
                <div class="row mt-3">
                    <div class="col-sm-12 font-weight-light" style="height:4rem">
                        @if (Model.Sinopse.Length > 60)
                        {
                            <small class="">@(Model.Sinopse.Substring(0, 60) + "...")</small>
                        }
                        else
                        {

                            <small class="">@(Model.Sinopse)</small>
                        }

                    </div>
                    <div class="col-sm-12 mt-3 text-dark">
                        <h5>R$ @(Model.Preco.ToString("0.00").Replace('.',','))</h5>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row no-gutters justify-content-sm-around">
                        <button type="button" class="btn btn-outline-success col-8" onclick="window.location.href='@(Url.Action("Descricao","Livros"))?codBar=@(Model.CodigoBarras)'" style="font-size:0.75rem">SAIBA MAIS</button>
                        <button type="button" class="btn btn-success col-3 addToCarrinho" value="@Model.CodigoBarras" style="font-size:0.75rem"><i class="fa fa-shopping-cart"></i></button>
                </div>
            </div>
        </div>
    </div>